# Generated by Django 5.1.3 on 2024-11-23 00:41

import app_user.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', app_user.managers.UserModelManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
